# fly.toml app configuration file generated for nuspherebackend on 2025-01-24T20:17:58+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nusphere-backend'
primary_region = 'sin'

[env]
  PORT = '8000'

[build]
  dockerfile = "Dockerfile" 

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
